### ISSUE TITLE
[1.18.2, Forge/Magma] Server crash on launch while using Flan

### ISSUE THREAD

**Issue by HonzaVinCZ** [Flemmli97/Flan#169]
### Modloader

Forge

### Minecraft version

1.18.2

### Modloader version

Magma 1.18.2-40.1.54-90e954f1

### Mod version

flan-1.18.2-1.7.10-forge.jar

### Description

There is a crash happening when trying to launch Magma server with Flan. Happens just after launch.

Magma Foundation release:
https://git.magmafoundation.org/magmafoundation/Magma-1-18-x/-/releases/90e954f1

`Exception in thread "main" java.lang.module.ResolutionException: Modules org.yaml.snakeyaml and flan export package org.yaml.snakeyaml.serializer to module appleskin
        at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
        at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
        at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
        at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
`

### Steps to reproduce

Install Magma Server, add Flan, launch server

### Logs

https://gist.github.com/HonzaVinCZ/4c9c03ac6ecf98c31500dd3fb70f6f61

**Comment by Flemmli97** [comment]
magma and any other mixed loader is not supported. only forge or fabric
