### ISSUE TITLE
Issue with Supplementaries mod

### ISSUE THREAD

**Issue by guangroove** [Flemmli97/Flan#295]
### Modloader

Fabric

### Minecraft version

1.20.1

### Modloader version

0.15.10

### Mod version

1.10.4

### Description

i'm trying to use this mod with Supplementaries mod, and crash after a couple of minuntes, both on singleplayer and server, when i use a chest

### Steps to reproduce

1. Step one: Use a chest or a door

### Mods that might affect the issue

Supplementaries mod

### Logs

[13:34:22] [Render thread/ERROR]: Error executing task on Client
java.lang.IndexOutOfBoundsException: Index 58 out of bounds for length 57
	at jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Unknown Source) ~[?:?]
	at java.util.Objects.checkIndex(Unknown Source) ~[?:?]
	at java.util.ArrayList.get(Unknown Source) ~[?:?]
	at net.minecraft.class_2371.get(class_2371.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_1703.method_7611(class_1703.java:287) ~[client-intermediary.jar:?]
	at net.minecraft.class_1703.method_7619(class_1703.java:591) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11109(class_634.java:1232) ~[client-intermediary.jar:?]
	at net.minecraft.class_2653.method_11451(class_2653.java:41) ~[client-intermediary.jar:?]
	at net.minecraft.class_2653.method_11054(class_2653.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.15.10.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.10.jar:?]
[13:34:37] [Render thread/INFO]: Loaded 286 advancements
[13:34:44] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: io/github/flemmli97/flan/api/permission/PermissionRegistry
	at net.mehvahdjukaar.supplementaries.integration.FlanCompat.canPlace(FlanCompat.java:33) ~[supplementaries-1.20-2.8.10-fabric.jar:?]
	at net.mehvahdjukaar.supplementaries.common.events.overrides.InteractEventsHandler.onItemUsedOnBlock(InteractEventsHandler.java:151) ~[supplementaries-1.20-2.8.10-fabric.jar:?]
	at net.mehvahdjukaar.supplementaries.common.events.ServerEvents.onRightClickBlock(ServerEvents.java:79) ~[supplementaries-1.20-2.8.10-fabric.jar:?]
	at net.mehvahdjukaar.supplementaries.common.events.fabric.ServerEventsFabric.onRightClickBlock(ServerEventsFabric.java:73) ~[supplementaries-1.20-2.8.10-fabric.jar:?]
	at net.fabricmc.fabric.api.event.player.UseBlockCallback.lambda$static$0(UseBlockCallback.java:41) ~[fabric-events-interaction-v0-0.6+1802ada577-6fc36030f9858a64.jar:?]
	at net.minecraft.class_3225.handler$dfk000$fabric-events-interaction-v0$interactBlock(class_3225.java:1587) ~[client-intermediary.jar:?]
	at net.minecraft.class_3225.method_14262(class_3225.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12046(class_3244.java:1140) ~[client-intermediary.jar:?]
	at net.minecraft.class_2885.method_12547(class_2885.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ClassNotFoundException: io.github.flemmli97.flan.api.permission.PermissionRegistry
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.10.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	... 24 more

**Comment by Flemmli97** [comment]
update supplementaries
