### ISSUE TITLE
[MOD COMPATIBILITY] Colonies Mod Compatibility

### ISSUE THREAD

**Issue by Strike5223** [Flemmli97/Flan#47]
I was wondering if there are any plans on adding compatibility to the colonies fabric mod.

**Comment by Flemmli97** [comment]
idk the mod. whats not compatible

**Comment by Strike5223** [comment]
Colonies is a mod that is similar to the factions plugin but for fabric.

```
java.lang.NoSuchFieldError: claimData
    at net.minecraft.class_3218.handler$zla002$initData(class_3218.java:4057)
    at net.minecraft.class_3218.<init>(class_3218.java:213)
    at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:368)
    at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:335)
    at net.minecraft.class_3176.method_3823(class_3176.java:179)
    at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645)
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
    at java.lang.Thread.run(Unknown Source)

```
https://www.curseforge.com/minecraft/mc-mods/colonies

**Comment by Flemmli97** [comment]
well sadly the mod is both arr (well arr with extra steps) and closed source so nothing i can do

**Comment by Strike5223** [comment]
Fair enough thanks for the response.
