### ISSUE TITLE
crash on startup with new flan 1.5.3

### ISSUE THREAD

**Issue by ghost** [Flemmli97/Flan#74]
crash on startup with new flan 1.5.3
 with 1.4.2 server run normaly

log: https://pastebin.com/8y3hTu7r

mc: 1.17
api: 0.36.0
flan: 1.5.3

**Comment by ghost** [comment]
any information? I need to sort this out as soon as possible.

**Comment by Wesley1808** [comment]
You can temporarily avoid this problem by setting inactivityTimeDays to -1 in the config file. That worked for us at least.

**Comment by ghost** [comment]
everything seems to be working.. thanks for the advice

**Comment by ghost** [comment]
and there's also a problem when you open a book in the lectern in admin claim the server crashes 
edit: interaction with any block crashes the server [cartography,fletching,smithing tables]

[Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'void net.minecraft.class_2653.<init>(int, int, net.minecraft.class_1799)'
at io.github.flemmli97.flan.event.ItemInteractEvents.updateHeldItem(ItemInteractEvents.java:139) ~[flan-1.17-1.5.3.jar:?]
at io.github.flemmli97.flan.event.ItemInteractEvents.onItemUseBlock(ItemInteractEvents.java:129) ~[flan-1.17-1.5.3.jar:?]
at net.minecraft.class_1799.handler$zbe000$blockUse(class_1799.java:1187) ~[intermediary-server.jar:?]
at net.minecraft.class_1799.method_7981(class_1799.java) ~[intermediary-server.jar:?]
