### ISSUE TITLE
Interacting with entities inside a claim causes a server crash

### ISSUE THREAD

**Issue by cherie535** [Flemmli97/Flan#75]
Interacting with a chest or a stick inside a claim causes a server crash

`[07:21:31] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'com.mojang.authlib.GameProfile net.minecraft.class_3312.method_14512(java.util.UUID)'
        at io.github.flemmli97.flan.event.ItemInteractEvents.inspect(ItemInteractEvents.java:253) ~[flan-1.17-1.5.3.jar:?]
        at io.github.flemmli97.flan.event.BlockInteractEvents.useBlocks(BlockInteractEvents.java:73) ~[flan-1.17-1.5.3.jar:?]
        at net.minecraft.class_4970$class_4971.handler$zzm000$useBlock(class_4970.java:1133) ~[intermediary-server.jar:?]
        at net.minecraft.class_4970$class_4971.method_26174(class_4970.java) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.redirect$bbl000$activateWithOptionalCactus(class_3225.java:2029) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java:327) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1050) ~[intermediary-server.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:30) ~[intermediary-server.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:110) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:748) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zop000$modifiedRunLoop(MinecraftServer.java:4899) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
`

**Comment by SnaveSutit** [comment]
I'm also having this issue using the mod in minecraft 1.17.1 and flan-1.17-1.5.3.jar

[crash-2021-07-12_00.38.30-server.txt](https://github.com/Flemmli97/Flan/files/6797954/crash-2021-07-12_00.38.30-server.txt)

**Comment by FredMund0** [comment]
It also happens when placing blocks

**Comment by SnaveSutit** [comment]
I've found that all of these actions cause the crash (Will add more to the list as I find them):
- Interacting with any entity inside of a claim
- Right clicking on a block with a stick in a claim
- Placing blocks
